ckpt_path: '/VOLUME/nia_vent_asynchrony/result/pilot/2022-10-31-08-55-01/ventdys_model.pt'
label_path: '/ext_ssd2/nia_vent/label_annotation'
data_path: 
- /VOLUME/nia_vent_asynchrony/data/processed_data/snu/instance_snu_1-300_1-379_120019_2022-10-27.pkl
test_id:
- 1-300
result_path: '/VOLUME/nia_vent_asynchrony/result/pilot'
CUDA_VISIBLE_DEVICES: 3
